# Generated by Django 2.0.5 on 2019-07-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phones', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='phones',
            field=models.ManyToManyField(related_name='articles', to='phones.Phone'),
        ),
    ]
