# Generated by Django 2.2.2 on 2019-07-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='a'),
            preserve_default=False,
        ),
    ]
