# Generated by Django 2.0.5 on 2019-07-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='a', max_length=64),
            preserve_default=False,
        ),
    ]
