# Generated by Django 2.2.2 on 2019-07-24 18:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_slug'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='customer.ProductCustomer', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='productcustomer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Order'),
        ),
        migrations.AddField(
            model_name='productcustomer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
