# Generated by Django 2.0.5 on 2019-07-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='customers', to='shop.Product'),
        ),
    ]
