# Generated by Django 2.2.2 on 2019-07-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20190724_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcustomer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qty', to='customer.Order'),
        ),
    ]
