# Generated by Django 2.2.2 on 2019-07-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190724_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcustomer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_info', to='customer.Order'),
        ),
        migrations.AlterField(
            model_name='productcustomercart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_info', to='customer.Customer'),
        ),
    ]
