# Generated by Django 2.0.5 on 2019-07-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.IntegerField()),
                ('ddr', models.IntegerField()),
                ('screen_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('screen_width_px', models.IntegerField()),
                ('screen_height_px', models.IntegerField()),
                ('description', models.TextField()),
                ('base_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_info', to='shop.Product')),
                ('category', models.ManyToManyField(related_name='product', to='shop.Category')),
            ],
        ),
    ]
