# Generated by Django 2.0.5 on 2019-07-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('memory', models.IntegerField()),
                ('ddr', models.IntegerField()),
                ('screen_size', models.FloatField()),
                ('screen_width_px', models.IntegerField()),
                ('screen_height_px', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
