# Generated by Django 2.0.5 on 2019-07-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='category',
        ),
    ]
