# Generated by Django 2.0.5 on 2019-07-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_remove_phone_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='description',
        ),
    ]
